name: All Model Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest tensorflow requests
    - name: Download Models
      run: |
        mkdir -p models
        wget https://github.com/LCIT-W25/AISC-T3-Grp4/releases/download/vgg_rnn_gru/best_hyperparameter_gru_model.h5 -O models/gru_model.h5
        wget https://github.com/LCIT-W25/AISC-T3-Grp4/releases/download/vgg_rnn_gru/best_rnn_model.h5 -O models/vgg_model.h5
        wget https://github.com/LCIT-W25/AISC-T3-Grp4/releases/download/vgg_rnn_gru/VGG16CLASSIFIER.h5 -O models/rnn_model.h5
    - name: Resave Models
      run: |
        python -c "import tensorflow as tf; model_paths = ['models/gru_model.h5', 'models/vgg_model.h5', 'models/rnn_model.h5']; for path in model_paths: try: model = tf.keras.models.load_model(path); model.save(path); print(f'Model resaved successfully: {path}'); except Exception as e: print(f'Error resaving model {path}: {e}')"
    - name: Run tests
      run: |
        pytest tests/test_models.py
